### ISSUE TITLE
brainmage.py get_channel_keys_and_train_paths may be GANDLF specific

### ISSUE THREAD

**Issue by smatzek** [FETS-AI/Algorithms#19]
**Describe the bug**

The [get_channel_keys_and_train_paths method in brainmage.py](https://github.com/FETS-AI/Algorithms/blob/c7276570eb9483cdd57978a4ea7ce109a08845f0/fets/models/pytorch/brainmage/brainmage.py#L175
), appears to be specific to the GANDLF dataloader.

I had to comment out its call when trying to use model /fets/models/pytorch/pt_3dresunet/pt_3dresunet.py with the fets/data/pytorch/ptbrainmagedata.py loader. I am using https://github.com/IntelLabs/OpenFederatedLearning without using the FETS front end.

**To Reproduce**
I hit this with OpenFederatedLearning at commit 38c946e850bc6958cb157db92b5dff6db4d3899c with the Algorithms submodule updated to commit 63f233f41559e67bb2c380178df3250364cc321b

**Expected behavior**
The pt_3dresunet.py model should work with the ptbrainimagedata.py loader.

**Screenshots**

**FeTS Version**
Version information is found on Help > About

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Linux (include detailed distro information)/macOS]
 - Version (including Build information, if any): [e.g. Fedora 22 or Windows 10.1803]

**Additional context**
I was attempting to get the pt_3dresunet.py model to train and converge from random initial weights using the BraTS 2017 data. It would not converge using OpenFederatedLearning at 38c946e850bc6958cb157db92b5dff6db4d3899c with the Algorithms hash it had. Seeing that various updates had occurred in Algorithms and the plots of the curves in https://github.com/FETS-AI/Algorithms/blob/master/fets/bin/plot_fed_training_curves/InspectFederation.ipynb showed similar non-convergence I decided to try and update the Algorithms hash to a later version to see if it would converge.

As it turns out, after commenting out the call to get_channel_keys_and_train_paths and other GANDLF uses, since I can't get that repository (private repo?), the model training runs out of memory on my 16GB GPU.

**Comment by sarthakpati** [comment]
Hi,

I would not recommend building from source as not all dependencies are available (yet). It will be soon, though. Thanks for your interest!
