### ISSUE TITLE
Install error while conduct setup.py in 'https://github.com/FETS-AI/Challenge/tree/main/Task_1'

### ISSUE THREAD

**Issue by danny0628** [FeTS-AI/Algorithms#94]
Hello, @sarthakpati 
When I run ` pip install .`  , the following error occurs.  I know this error occur in setup.py line 34 `'fets @ git+https://github.com/FETS-AI/Algorithms.git@fets_challenge'`
Can you help me with this?
![Screenshot from 2024-05-14 17-07-08](https://github.com/FeTS-AI/Algorithms/assets/32856219/42e0abdc-412c-4d21-acf7-d4cbe29dd811)

Thank you.

**Comment by sarthakpati** [comment]
In the file `.gitmodules`, can you try changing the `url` to `https://github.com/mlcommons/GANDLF.git`?

**Comment by danny0628** [comment]
I did git cloned the Algorithms repository and placed it inside Task_1. 
The problem is solved

**Comment by sarthakpati** [comment]
Glad to hear that.

**Comment by danny0628** [comment]
In my case,
First, Place the file structure as follows:
![Screenshot from 2024-05-21 10-31-00](https://github.com/FeTS-AI/Algorithms/assets/32856219/f74b07bd-83a8-4eba-9b51-5c5690032d15)

Second, `Task_1/Algorithms/.gitmodules` file change it to:
```
[submodule "GANDLF_module"] 
	path = GANDLF_module
	url = https://github.com/mlcommons/GANDLF.git
```
Last, `Task_1/setup.py` line 33 ` 'fets @ git+https://github.com/FETS-AI/Algorithms.git@fets_challenge' ` --> remove it
